In [1]:
import pickle
import numpy as np
import pandas as pd
from sklearn.externals import joblib
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_validate
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
#Read CSV, index+1 supaya index dimulai dari 1, tidak 0, memudahkan pembacaan dataframe dibawah.
colomn = ["Clump_Thickness","Uniformity_of_Cell_Size","Uniformity_of_Cell_Shape","Marginal_Adhesion","Single_Epithelial_Cell_Size","Bare_Nuclei","Bland_Chromatin","Normal_Nucleoli","Mitoses","Class","Klasifikasi"]
df = pd.read_csv('coba.csv', names = colomn, delimiter=';')
df.index += 1

In [20]:
#melihat dataframe diabetes.csv
df.head()

Clump_Thickness  Uniformity_of_Cell_Size  Uniformity_of_Cell_Shape  \
1                5                        1                         1   
2                5                        4                         4   
3                3                        1                         1   
4                6                        8                         8   
5                4                        1                         1   

   Marginal_Adhesion  Single_Epithelial_Cell_Size Bare_Nuclei  \
1                  1                            2           1   
2                  5                            7          10   
3                  1                            2           2   
4                  1                            3           4   
5                  3                            2           1   

   Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  Klasifikasi  
1                3                1        1      2            0  
2                3                2        1      2            0  
3                3                1        1      2            0  
4                3                7        1      2            0  
5                3                1        1      2            0

In [21]:
df.dtypes

Clump_Thickness                 int64
Uniformity_of_Cell_Size         int64
Uniformity_of_Cell_Shape        int64
Marginal_Adhesion               int64
Single_Epithelial_Cell_Size     int64
Bare_Nuclei                    object
Bland_Chromatin                 int64
Normal_Nucleoli                 int64
Mitoses                         int64
Class                           int64
Klasifikasi                     int64
dtype: object

In [22]:
#Pre-Processing
data = pd.DataFrame(data=df)
data = data[data.Bare_Nuclei != "?"]
data = data.apply(pd.to_numeric)

In [24]:
data.dtypes

Clump_Thickness                int64
Uniformity_of_Cell_Size        int64
Uniformity_of_Cell_Shape       int64
Marginal_Adhesion              int64
Single_Epithelial_Cell_Size    int64
Bare_Nuclei                    int64
Bland_Chromatin                int64
Normal_Nucleoli                int64
Mitoses                        int64
Class                          int64
Klasifikasi                    int64
dtype: object

In [5]:
#penentuan atribut
np_target = data['Klasifikasi'].values
np_data = data.iloc[:,:-2].values

In [6]:
#Split dataset, 30% testing 70% training.
X_train, X_test, y_train, y_test = train_test_split(np_data,np_target,test_size=0.3, random_state=None)

In [7]:
#Naive Bayes (Gaussian)
clf = GaussianNB().fit(X_train, y_train)

In [8]:
X_train

array([[ 5,  3,  5, ...,  5,  3,  1],
       [ 1,  1,  1, ...,  3,  1,  1],
       [ 5,  1,  1, ...,  3,  2,  1],
       ...,
       [10,  4,  5, ...,  4,  1,  1],
       [ 2,  1,  1, ...,  3,  1,  1],
       [ 2,  1,  1, ...,  2,  1,  1]], dtype=int64)

In [9]:
#Cuma buat liat ukuran data train vs data test
len(X_train), len(X_test)

(478, 205)

In [10]:
#Fit model naive bayes sesuai data training (proses training model)
clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [11]:
#CrossValidation model yang sudah dibangun. Dengan parameter scoring=accuracy,precision, dan recall
scoring = ['accuracy', 'precision', 'recall']
scores = cross_validate(clf, X_test, y_test, scoring=scoring, cv=10, return_train_score=True)

In [12]:
#Menampilkan hasil dari cross validation
scores

{'fit_time': array([0.00553226, 0.00300217, 0.00400376, 0.00299978, 0.00500321,
        0.03453517, 0.00500393, 0.01400137, 0.00300503, 0.00200057]),
 'score_time': array([0.02600479, 0.01099753, 0.01099944, 0.0140028 , 0.01455498,
        0.06301475, 0.01804638, 0.01600242, 0.01900387, 0.02100348]),
 'test_accuracy': array([0.95238095, 0.85714286, 0.95238095, 0.95238095, 1.        ,
        1.        , 0.9       , 0.95      , 1.        , 1.        ]),
 'train_accuracy': array([0.96195652, 0.97282609, 0.96195652, 0.96195652, 0.95652174,
        0.95675676, 0.96756757, 0.95675676, 0.95675676, 0.95675676]),
 'test_precision': array([1.        , 0.7       , 0.875     , 0.875     , 1.        ,
        1.        , 0.85714286, 0.875     , 1.        , 1.        ]),
 'train_precision': array([0.91176471, 0.93939394, 0.92424242, 0.91176471, 0.91044776,
        0.91044776, 0.92537313, 0.91044776, 0.91044776, 0.91044776]),
 'test_recall': array([0.85714286, 1.        , 1.        , 1.        , 1. 

In [13]:
#menampilkan test_accuracy dari cross validation, memiliki 10 value, tiap value adalah representasi akurasi dari tiap iterasi
scores['test_accuracy']

array([0.95238095, 0.85714286, 0.95238095, 0.95238095, 1.        ,
       1.        , 0.9       , 0.95      , 1.        , 1.        ])

In [14]:
#Hasil cross validation berupa dictionary. Kemudian dictionary disimpan menjadi dataframe. Hanya untuk keperluan pembacaan
df_scores = pd.DataFrame.from_dict(scores)
df_scores.index +=1
df_scores

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
1   0.005532    0.026005       0.952381        0.961957        1.000000   
2   0.003002    0.010998       0.857143        0.972826        0.700000   
3   0.004004    0.010999       0.952381        0.961957        0.875000   
4   0.003000    0.014003       0.952381        0.961957        0.875000   
5   0.005003    0.014555       1.000000        0.956522        1.000000   
6   0.034535    0.063015       1.000000        0.956757        1.000000   
7   0.005004    0.018046       0.900000        0.967568        0.857143   
8   0.014001    0.016002       0.950000        0.956757        0.875000   
9   0.003005    0.019004       1.000000        0.956757        1.000000   
10  0.002001    0.021003       1.000000        0.956757        1.000000   

    train_precision  test_recall  train_recall  
1          0.911765     0.857143      0.984127  
2          0.939394     1.000000      0.984127  
3          0.924242     1.000000      0.968254  
4          0.911765     1.000000      0.984127  
5          0.910448     1.000000      0.968254  
6          0.910448     1.000000      0.968254  
7          0.925373     0.857143      0.984127  
8          0.910448     1.000000      0.968254  
9          0.910448     1.000000      0.968254  
10         0.910448     1.000000      0.968254

In [15]:
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9609756097560975


In [16]:
precision_score(y_test, y_pred, average=None)

array([0.99224806, 0.90789474])

In [17]:
recall_score(y_test, y_pred, average=None)

array([0.94814815, 0.98571429])

In [18]:
#DUMP MODEL YANG SUDAH DIBUAT AGAR MENJADI MODEL PERSISTENCE DAN LANGSUNG DIGUNAKAN DITEMPAT LAIN.
#joblib.dump(clf, 'praktikum1_svc.pkl') 

In [19]:
#DUMP MODEL!!
pickle.dump(clf, open('model.pkl','wb'))